apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "hf-operator.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "hf-operator.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name | default .Chart.Name }}
    namespace: {{ .Values.namespace }}
