apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hf-operator.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "hf-operator.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "hf-operator.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "hf-operator.name" . }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name | default .Chart.Name }}
      containers:
        - name: manager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--metrics-bind-address=0.0.0.0:8080"
            - "--health-probe-bind-address=:8081"
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
