# Extra RBAC (if needed in namespace)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "hf-operator.name" . }}-ns
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "hf-operator.name" . }}-ns-binding
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name | default .Chart.Name }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: {{ include "hf-operator.name" . }}-ns
  apiGroup: rbac.authorization.k8s.io
