apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default .Chart.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "hf-operator.name" . }}
