# This rule is not used by the project hf-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over hfops.kamal.dev.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: hf-operator
    app.kubernetes.io/managed-by: kustomize
  name: modeldownload-admin-role
rules:
- apiGroups:
  - hfops.kamal.dev
  resources:
  - modeldownloads
  verbs:
  - '*'
- apiGroups:
  - hfops.kamal.dev
  resources:
  - modeldownloads/status
  verbs:
  - get
