# This rule is not used by the project hf-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to hfops.kamal.dev resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: hf-operator
    app.kubernetes.io/managed-by: kustomize
  name: modeldownload-viewer-role
rules:
- apiGroups:
  - hfops.kamal.dev
  resources:
  - modeldownloads
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hfops.kamal.dev
  resources:
  - modeldownloads/status
  verbs:
  - get
