replicaCount: 1

image:
  repository: ghcr.io/skamalj/hf-operator
  tag: latest
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: hf-operator

rbac:
  create: true

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

# Configure default namespace (install with --namespace)
namespace: default

# CRD installed by helm as static resource in crds/
installCRDs: true
